server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cdkim1226/spring-cloud-config.git
#          private 저장소일때
#          username: [your username]
#          password: [your password]